[package]
name = "nexus-queue"
description = "High-performance lock-free ring buffer queues for trading systems"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords = ["spsc", "mpsc", "ring-buffer", "queue", "lock-free"]
categories = ["concurrency", "data-structures", "no-std"]

[dependencies]
crossbeam-utils = "0.8.21"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
crossbeam-queue = "0.3.12"
rtrb = "0.3.2"

[lints]
workspace = true

[[bench]]
name = "spsc"
harness = false

[[bench]]
name = "mpsc"
harness = false

[[bench]]
name = "profile_spsc"
harness = false

[[bench]]
name = "perf_raw"
harness = false

[[bench]]
name = "perf_minimal"
harness = false

[[bench]]
name = "perf_rtrb"
harness = false

[[bench]]
name = "perf_rtrb_clone"
harness = false

[[bench]]
name = "perf_const"
harness = false

[[bench]]
name = "perf_fenced"
harness = false

[[bench]]
name = "perf_raw_fenced"
harness = false

[[bench]]
name = "perf_raw_pointer"
harness = false

